In [1]:
import pandas as pd
df = pd.read_csv('Bookings - July.csv')

In [2]:
df.head(10)

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 3:15:00,3:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 9:02:00,9:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...
5,2024-07-13 4:42:00,4:42:00,CNR8787177882,Success,CID802429,Mini,Kadugodi,Vijayanagar,231.0,90.0,NaN,NaN,No,NaN,173,UPI,41,3.4,4.6,https://cdn-icons-png.flaticon.com/128/3202/32...
6,2024-07-23 9:51:00,9:51:00,CNR3612067560,Success,CID476071,Bike,Tumkur Road,Whitefield,133.0,40.0,NaN,NaN,No,NaN,140,Cash,49,3.2,4.5,https://cdn-icons-png.flaticon.com/128/9983/99...
7,2024-07-11 11:12:00,11:12:00,CNR5374902489,Canceled by Driver,CID735691,Prime Plus,Bannerghatta Road,Sarjapur Road,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,344,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/11409/1...
8,2024-07-01 19:19:00,19:19:00,CNR5030602354,Driver Not Found,CID999840,Mini,Chamarajpet,Peenya,NaN,NaN,NaN,NaN,NaN,NaN,839,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/3202/32...
9,2024-07-18 1:31:00,1:31:00,CNR6328453219,Canceled by Driver,CID907133,Auto,RT Nagar,Varthur,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,893,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/16526/1...

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  str
 1   Time                        103024 non-null  str
 2   Booking_ID                  103024 non-null  str
 3   Booking_Status              103024 non-null  str
 4   Customer_ID                 103024 non-null  str
 5   Vehicle_Type                103024 non-null  str
 6   Pickup_Location             103024 non-null  str
 7   Drop_Location               103024 non-null  str
 8   V_TAT                       63967 non-null   float64
 9   C_TAT                       63967 non-null   float64
 10  Canceled_Rides_by_Customer  10499 non-null   str
 11  Canceled_Rides_by_Driver    18434 non-null   str
 12  Incomplete_Rides            63967 non-null   str
 13  Incomplete_Rides_Reason     3926 non-null    str
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              63967 non-null   str
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Vehicle Images              103024 non-null  str
dtypes: float64(4), int64(2), str(14)
memory usage: 15.7 MB

In [4]:
df.describe()

,V_TAT,C_TAT,Booking_Value,Ride_Distance,Driver_Ratings,Customer_Rating
count,63967.000000,63967.000000,103024.000000,103024.000000,63967.000000,63967.000000
mean,170.876952,84.873372,548.751883,14.189927,3.997457,3.998313
std,80.803640,36.005100,536.541221,15.776270,0.576834,0.578957
min,35.000000,25.000000,100.000000,0.000000,3.000000,3.000000
25%,98.000000,55.000000,242.000000,0.000000,3.500000,3.500000
50%,168.000000,85.000000,386.000000,8.000000,4.000000,4.000000
75%,238.000000,115.000000,621.000000,26.000000,4.500000,4.500000
max,308.000000,145.000000,2999.000000,49.000000,5.000000,5.000000

In [5]:
df.describe(include='all')

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
count,103024,103024,103024,103024,103024,103024,103024,103024,63967.000000,63967.000000,10499,18434,63967,3926,103024.000000,63967,103024.000000,63967.000000,63967.000000,103024
unique,40214,1440,103024,4,94544,7,50,50,NaN,NaN,5,4,2,3,NaN,4,NaN,NaN,NaN,7
top,2024-07-12 12:38:00,0:53:00,CNR7153255142,Success,CID954071,Prime Sedan,Banashankari,Peenya,NaN,NaN,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,NaN,Cash,NaN,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
freq,10,101,1,63967,5,14877,2201,2159,NaN,NaN,3175,6542,60041,1601,NaN,35022,NaN,NaN,NaN,14877
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170.876952,84.873372,NaN,NaN,NaN,NaN,548.751883,NaN,14.189927,3.997457,3.998313,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.803640,36.005100,NaN,NaN,NaN,NaN,536.541221,NaN,15.776270,0.576834,0.578957,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.000000,25.000000,NaN,NaN,NaN,NaN,100.000000,NaN,0.000000,3.000000,3.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.000000,55.000000,NaN,NaN,NaN,NaN,242.000000,NaN,0.000000,3.500000,3.500000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168.000000,85.000000,NaN,NaN,NaN,NaN,386.000000,NaN,8.000000,4.000000,4.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,238.000000,115.000000,NaN,NaN,NaN,NaN,621.000000,NaN,26.000000,4.500000,4.500000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,308.000000,145.000000,NaN,NaN,NaN,NaN,2999.000000,NaN,49.000000,5.000000,5.000000,NaN

In [6]:
df.isnull().sum()

Date                              0
Time                              0
Booking_ID                        0
Booking_Status                    0
Customer_ID                       0
Vehicle_Type                      0
Pickup_Location                   0
Drop_Location                     0
V_TAT                         39057
C_TAT                         39057
Canceled_Rides_by_Customer    92525
Canceled_Rides_by_Driver      84590
Incomplete_Rides              39057
Incomplete_Rides_Reason       99098
Booking_Value                     0
Payment_Method                39057
Ride_Distance                     0
Driver_Ratings                39057
Customer_Rating               39057
Vehicle Images                    0
dtype: int64

In [7]:
df.columns

Index(['Date', 'Time', 'Booking_ID', 'Booking_Status', 'Customer_ID',
       'Vehicle_Type', 'Pickup_Location', 'Drop_Location', 'V_TAT', 'C_TAT',
       'Canceled_Rides_by_Customer', 'Canceled_Rides_by_Driver',
       'Incomplete_Rides', 'Incomplete_Rides_Reason', 'Booking_Value',
       'Payment_Method', 'Ride_Distance', 'Driver_Ratings', 'Customer_Rating',
       'Vehicle Images'],
      dtype='str')

## Connecting Python script to PostgreSQL

In [8]:
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\data analytics\data analytics\ola data analyst\dataenv\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\data analytics\data analytics\ola data analyst\dataenv\lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in c:\data analytics\data analytics\ola data analyst\dataenv\lib\site-packages (from sqlalchemy) (3.5.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\data analytics\data analytics\ola data analyst\dataenv\lib\site-packages (from sqlalchemy) (4.16.0)

[notice] A new release of pip is available: 24.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
from sqlalchemy import create_engine
from urllib.parse import quote_plus


username = "postgres" # default username for PostgreSQL
# password = "Sumeet@123" # the password you set during installation
password = quote_plus("Sumeet@123") 
host = "localhost" # if running local
port = 5432 # default PostgreSQL port 
database = "ola" # the database you created in pgAdmin4

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

## Step 2: Load DataFrame into PostgreSQL
table_name = "bookings" # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully Loaded into table '{table_name}' in database '{database}'.")

Data successfully Loaded into table 'bookings' in database 'ola'.

## Code for MySQL

In [12]:
!pip install pymysql sqlalchemy

Collecting pymysql
  Using cached pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: sqlalchemy in c:\data analytics\data analytics\ola data analyst\dataenv\lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in c:\data analytics\data analytics\ola data analyst\dataenv\lib\site-packages (from sqlalchemy) (3.5.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\data analytics\data analytics\ola data analyst\dataenv\lib\site-packages (from sqlalchemy) (4.16.0)
Using cached pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

[notice] A new release of pip is available: 24.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
from sqlalchemy import create_engine

# MySQL connection
username = "root"
password = "root"
host = "localhost"
port = "3306"
database = "ola"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# Write DataFrame to MySQL
table_name = "bookings"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
pd.read_sql("SELECT * FROM bookings LIMIT 5;", engine)

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,None,444,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,None,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,None,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 3:15:00,3:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,None,384,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 9:02:00,9:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,None,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...